/* Core/Src/bmi270_port.c */

#include "bmi270_port.h"
#include "main.h" // Required for HAL handles and definitions
#include "stm32u3xx_hal.h"

// Timeout for I2C operations (milliseconds)
#define BMI270_I2C_TIMEOUT 100

// --- HAL Handle Extern Declarations (Ensure these match your main.c) ---
extern I2C_HandleTypeDef hi2c1;
// -----------------------------------------------------------------------

/**
 * @brief Microsecond delay function (implementation depends on system clock)
 */
void bmi2_delay_us(uint32_t period, void *intf_ptr) {
    (void)intf_ptr; // Unused parameter

    // Simple implementation using HAL_Delay for ms, potentially inaccurate for small us values
    if (period >= 1000) {
        HAL_Delay(period / 1000);
    } else {
         // Busy-wait loop for sub-millisecond delays (approximate)
         // Requires accurate SystemCoreClock definition and optimization level awareness
         // Consider using DWT cycle counter or a dedicated timer for better accuracy
         uint32_t wait_loop_index = (period * (SystemCoreClock / 1000000U)) / 4U; // Adjust divisor based on loop overhead
         while(wait_loop_index != 0U)
         {
             wait_loop_index--;
         }
    }
}

/**
 * @brief I2C Write function wrapper for HAL
 */
int8_t bmi2_i2c_write(uint8_t reg_addr, const uint8_t *reg_data, uint32_t len, void *intf_ptr) {
    // NOTE: intf_ptr might point to the I2C Handle (&hi2c1) if set in bmi2_interface_init
    // Or, we can continue using the global handle directly. Let's use the global one for simplicity.
    (void)intf_ptr;

    // HAL I2C requires the address to be passed in the transmit function itself.
    // The BMI driver API separates reg_addr and data. We need to send the register
    // address first, then the data. HAL_I2C_Mem_Write is suitable here.
    HAL_StatusTypeDef status = HAL_I2C_Mem_Write(&hi2c1, BMI270_I2C_ADDR, reg_addr,
                                               I2C_MEMADD_SIZE_8BIT, (uint8_t*)reg_data, len, BMI270_I2C_TIMEOUT);

    if (status == HAL_OK) {
        return BMI2_OK;
    } else {
        // Map HAL error to BMI2 error (basic mapping)
        return BMI2_E_COM_FAIL;
    }
}

/**
 * @brief I2C Read function wrapper for HAL
 */
int8_t bmi2_i2c_read(uint8_t reg_addr, uint8_t *reg_data, uint32_t len, void *intf_ptr) {
    // NOTE: intf_ptr might point to the I2C Handle (&hi2c1) if set in bmi2_interface_init
    (void)intf_ptr;

    // Use HAL_I2C_Mem_Read to read from a specific register address
    HAL_StatusTypeDef status = HAL_I2C_Mem_Read(&hi2c1, BMI270_I2C_ADDR, reg_addr,
                                              I2C_MEMADD_SIZE_8BIT, reg_data, len, BMI270_I2C_TIMEOUT);

    if (status == HAL_OK) {
        return BMI2_OK;
    } else {
        return BMI2_E_COM_FAIL;
    }
}


/**
 * @brief Initialize the platform specific interface for BMI270
 */
int8_t bmi2_interface_init(struct bmi2_dev *bmi_dev) {
    if (bmi_dev == NULL) {
        return BMI2_E_NULL_PTR;
    }

    // Assign the function pointers in the device structure
    bmi_dev->intf = BMI2_I2C_INTF;
    bmi_dev->read = bmi2_i2c_read;
    bmi_dev->write = bmi2_i2c_write;
    bmi_dev->delay_us = bmi2_delay_us;

    // The driver itself doesn't store the I2C address in dev_id in this version.
    // The address (BMI270_I2C_ADDR) is used directly in read/write calls.

    // Pass the I2C handle via intf_ptr if the driver expects it for context.
    // If read/write functions don't use intf_ptr, this can be NULL.
    // Setting it is safer in case future driver versions or specific features use it.
    bmi_dev->intf_ptr = &hi2c1;

    // Set read/write length according to BMI2 driver requirements (check bmi2.h or examples)
    // Often used for SPI burst reads/writes, may not be critical for I2C mem reads/writes.
    // bmi_dev->read_write_len = 32; // Example, adjust if needed

    // No specific HAL initialization needed here, assuming I2C1 is already
    // initialized by the HAL_I2C_Init() called in main.c generated by CubeMX.

    return BMI2_OK;
}
