/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     Minimal System calls file
 *
 * For more information about which c-functions need which blend,
 * please refer to '/libc/README.md' in the GCC toolchain root
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
//#undef errno
extern int errno;
extern int __io_putchar(int ch) __attribute__((weak)); // Allow weak reference for printf redirection
extern int __io_getchar(void) __attribute__((weak)); // Allow weak reference

register char * stack_ptr asm("sp");

/* Functions */

/**
 * @brief _close Closes a file.
 * @param file: File handle.
 * @retval int: -1 on error with errno set (always error here).
 */
__attribute__((weak)) int _close(int file)
{
	(void)file; // Prevent unused warning
	errno = EBADF;
	return -1;
}

/**
 * @brief _lseek Sets position in a file.
 * @param file: File handle.
 * @param ptr: Offset.
 * @param dir: Direction (SEEK_SET, SEEK_CUR, SEEK_END).
 * @retval int: -1 on error with errno set (always error here).
 */
__attribute__((weak)) int _lseek(int file, int ptr, int dir)
{
	(void)file; // Prevent unused warning
	(void)ptr;  // Prevent unused warning
	(void)dir;  // Prevent unused warning
	errno = EBADF;
	return -1;
}

/**
 * @brief _read Reads from a file.
 * @param file: File handle.
 * @param ptr: Buffer to read into.
 * @param len: Number of bytes to read.
 * @retval int: 0 (end of file) or -1 on error (always error here).
 */
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
	(void)file; // Prevent unused warning
	(void)ptr;  // Prevent unused warning
	(void)len;  // Prevent unused warning

	// Return 0 to indicate EOF for stdin, or error for others
	if (file == 0) // stdin
		return 0;

	errno = EBADF;
	return -1;
}

/**
 * @brief _write Writes to a file. Can be redirected for printf.
 * @param file: File handle (1 for stdout, 2 for stderr).
 * @param ptr: Buffer to write from.
 * @param len: Number of bytes to write.
 * @retval int: Number of bytes written, or -1 on error.
 */
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
	int n;

	// Redirect stdout and stderr to __io_putchar if it's defined (e.g., for UART/SWO)
	if ((file == 1 || file == 2) && __io_putchar != NULL)
	{
		for (n = 0; n < len; n++)
		{
			__io_putchar(ptr[n]);
		}
		return len; // Return number of bytes written
	}

	// Otherwise, return error for other file descriptors
	errno = EBADF;
	return -1;
}


/**
 * @brief _exit Exits the program.
 * @param status: Exit status.
 */
__attribute__((weak)) void _exit(int status)
{
	(void)status; // Prevent unused warning
	while(1) {}		/* Make sure we hang here */
}

/**
 * @brief _kill Sends a signal to a process.
 * @param pid: Process ID.
 * @param sig: Signal number.
 * @retval int: -1 on error with errno set (always error here).
 */
__attribute__((weak)) int _kill(int pid, int sig)
{
	(void)pid; // Prevent unused warning
	(void)sig; // Prevent unused warning
	errno = EINVAL;
	return -1;
}

/**
 * @brief _getpid Gets the process ID.
 * @retval int: Always returns 1.
 */
__attribute__((weak)) int _getpid(void)
{
	return 1;
}

/**
 * @brief _fstat Gets file status.
 * @param file: File handle.
 * @param st: Pointer to stat structure.
 * @retval int: 0 on success, -1 on error (always error here).
 */
__attribute__((weak)) int _fstat(int file, struct stat *st)
{
	(void)file; // Prevent unused warning
	// Minimal implementation: Set file type to character device
	st->st_mode = S_IFCHR;
	return 0; // Pretend success for basic checks

	// Alternative: Return error
	// errno = EBADF;
	// return -1;
}

/**
 * @brief _isatty Checks if a file descriptor refers to a terminal.
 * @param file: File handle.
 * @retval int: 1 if it's a terminal (stdin, stdout, stderr), 0 otherwise.
 */
__attribute__((weak)) int _isatty(int file)
{
	if (file == 0 || file == 1 || file == 2) // stdin, stdout, stderr
		return 1;

	errno = EBADF;
	return 0;
}

/**
 * @brief Increase program data space.
 * As malloc and related functions depend on this, it is useful to have
 * a working implementation. The following implementation is provided for
 * initialization purposes only, and may not be suitable for all applications.
 * @param incr: Amount to increase the heap by.
 * @retval char*: Pointer to the previous end of heap on success, (char*)-1 on error.
 */
__attribute__((weak)) caddr_t _sbrk(int incr)
{
	extern char _end; // Symbol defined by the linker script marking the end of BSS
	static char *heap_end;
	char *prev_heap_end;

	if (heap_end == NULL)
	{
		heap_end = &_end;
	}

	prev_heap_end = heap_end;
	if (heap_end + incr > stack_ptr) // Check against stack pointer (simple check)
	{
		// Heap and stack collision
		errno = ENOMEM;
		return (caddr_t) -1;
	}

	heap_end += incr;

	return (caddr_t) prev_heap_end;
}

/* Register name faking - works in collusion with the linker.  */
register char * stack_ptr asm ("sp");
