/* Core/Src/temp_task.c */

#include "temp_task.h"
#include "main.h" // Required for HAL handles and definitions
#include "stm32u3xx_hal.h"
// Ensure ADC_SINGLE_ENDED is defined via HAL includes
// #include "stm32u3xx_hal_adc_ex.h" // Might need explicit include if not in conf.h
#include <stdio.h>  // For printf
#include <string.h> // For memset

// --- Configuration ---
#define TEMP_POLL_INTERVAL_MS (1000 / 1) // 1 Hz = 1000ms interval
#define ADC_TIMEOUT_MS        10
#define ADC_VREF_MV           3300.0f // ADC Reference Voltage in mV (Confirm based on VREF+ connection)
#define ADC_MAX_VALUE         4095.0f // For 12-bit ADC (2^12 - 1)

// TMP235A4 (A4 variant, 10mV/C, 500mV offset) - Based on datasheet
#define TEMP_SENSOR_SLOPE_MV_C  10.0f   // mV per degree C
#define TEMP_SENSOR_OFFSET_MV   500.0f  // mV at 0 degrees C

// --- HAL Handle Extern Declarations ---
extern ADC_HandleTypeDef hadc1;
// --------------------------------------

// --- Local Variables ---
static bool temp_initialized = false;
static uint32_t last_poll_time = 0;
static temp_data_t last_valid_data = { .temperature_c = 0.0f, .data_valid = false };
// ---------------------

/**
 * @brief Initializes the Temperature Sensor task (ADC peripheral).
 */
bool temp_task_init(void) {
    // ADC initialization is primarily handled by HAL_ADC_Init() generated by CubeMX.
    // ADC calibration is recommended for accuracy.
    // Use the HAL definition ADC_SINGLE_ENDED for the second argument.
    if (HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED) != HAL_OK) {
        printf("TEMP Error: ADC Calibration Failed\r\n");
        // Decide if this is acceptable or should be an error
        // return false;
    } else {
        printf("TEMP Info: ADC Calibration OK.\r\n");
    }

    temp_initialized = true;
    last_poll_time = HAL_GetTick();
    last_valid_data.data_valid = false;

    return true;
}

/**
 * @brief Performs a single run/update cycle for the Temperature task.
 */
bool temp_task_run(temp_data_t *p_temp_data) {
    HAL_StatusTypeDef status;
    uint32_t adc_raw_value = 0;
    bool new_data_acquired = false;

    if (!temp_initialized || p_temp_data == NULL) {
        return false;
    }

    uint32_t current_time = HAL_GetTick();
    if ((current_time - last_poll_time) >= TEMP_POLL_INTERVAL_MS) {
        last_poll_time = current_time;

        status = HAL_ADC_Start(&hadc1);
        if (status != HAL_OK) {
            printf("TEMP Error: HAL_ADC_Start failed (%d)\r\n", status);
            p_temp_data->data_valid = false; // Ensure data marked invalid on error
            memcpy(&last_valid_data, p_temp_data, sizeof(temp_data_t)); // Update last known state
            return false;
        }

        status = HAL_ADC_PollForConversion(&hadc1, ADC_TIMEOUT_MS);
        if (status != HAL_OK) {
            printf("TEMP Error: HAL_ADC_PollForConversion failed or timed out (%d)\r\n", status);
             HAL_ADC_Stop(&hadc1);
            p_temp_data->data_valid = false;
            memcpy(&last_valid_data, p_temp_data, sizeof(temp_data_t));
            return false;
        }

        adc_raw_value = HAL_ADC_GetValue(&hadc1);

        status = HAL_ADC_Stop(&hadc1);
         if (status != HAL_OK) {
             printf("TEMP Warning: HAL_ADC_Stop failed (%d)\r\n", status);
         }

        float voltage_mv = ((float)adc_raw_value / ADC_MAX_VALUE) * ADC_VREF_MV;
        p_temp_data->temperature_c = (voltage_mv - TEMP_SENSOR_OFFSET_MV) / TEMP_SENSOR_SLOPE_MV_C;
        p_temp_data->data_valid = true;
        new_data_acquired = true;

        memcpy(&last_valid_data, p_temp_data, sizeof(temp_data_t));

        // printf("TEMP: ADC=%lu, V=%.1fmV, T=%.2fC\r\n", adc_raw_value, voltage_mv, p_temp_data->temperature_c);

    } else {
        // If not polling time, provide the last known valid data
         memcpy(p_temp_data, &last_valid_data, sizeof(temp_data_t));
    }

    return new_data_acquired; // Return true only if new data was read this cycle
}


/**
 * @brief Get the last successfully read Temperature data.
 */
void temp_task_get_last_data(temp_data_t *p_temp_data) {
     if (p_temp_data != NULL) {
        memcpy(p_temp_data, &last_valid_data, sizeof(temp_data_t));
    }
}
