#include "usbx_device.h"
#include "ux_device_stack.h"
#include "ux_device_class_cdc_acm.h"
#include "usbx_device_descriptors.h"  // CubeMX-generated descriptors (ensure they are added)
#include "stm32u3xx_hal.h"
#include "stm32u3xx_hal_pcd.h"
#include "main.h"  // For Error_Handler

extern PCD_HandleTypeDef hpcd_USB_DRD_FS;

#define UX_DEVICE_MEM_POOL_SIZE    (8192u)
static UCHAR ux_device_mem_pool[UX_DEVICE_MEM_POOL_SIZE];

UX_SLAVE_CLASS_CDC_ACM *g_cdc_acm = UX_NULL;

void MX_USBX_Device_Init(void)
{
    UINT status;

    /* Initialize USBX system with our memory pool */
    status = ux_system_initialize(ux_device_mem_pool, UX_DEVICE_MEM_POOL_SIZE, UX_NULL, 0);
    if (status != UX_SUCCESS)
    {
        Error_Handler();
    }

    /* Initialize the USB device stack with full-speed descriptors.
       (USBD_device_framework_full_speed, USBD_string_framework, etc. are generated by CubeMX) */
    status = ux_device_stack_initialize(USBD_device_framework_full_speed,
                                        USBD_device_framework_full_speed_length,
                                        UX_NULL, 0,
                                        USBD_string_framework,
                                        USBD_string_framework_length,
                                        USBD_language_id_framework,
                                        USBD_language_id_framework_length,
                                        UX_NULL);
    if (status != UX_SUCCESS)
    {
        Error_Handler();
    }

    /* Register the CDC-ACM class with the USBX device stack */
    {
        UX_SLAVE_CLASS_CDC_ACM_PARAMETER cdc_acm_param;
        memset(&cdc_acm_param, 0, sizeof(cdc_acm_param));
        cdc_acm_param.ux_slave_class_cdc_acm_instance_activate   = USBD_CDC_ACM_Activate;
        cdc_acm_param.ux_slave_class_cdc_acm_instance_deactivate = USBD_CDC_ACM_Deactivate;
        cdc_acm_param.ux_slave_class_cdc_acm_parameter_change    = USBD_CDC_ACM_ParameterChange;

        UINT config_id = USBD_Get_Configuration_Number(CLASS_TYPE_CDC_ACM, 0);
        UINT interface_id = USBD_Get_Interface_Number(CLASS_TYPE_CDC_ACM, 0);

        status = ux_device_stack_class_register(_ux_system_slave_class_cdc_acm_name,
                                                ux_device_class_cdc_acm_entry,
                                                config_id, interface_id,
                                                (VOID *)&cdc_acm_param);
        if (status != UX_SUCCESS)
        {
            Error_Handler();
        }
    }

    /* Link the USBX DCD (Device Controller Driver) with the STM32 HAL PCD driver */
    status = ux_dcd_stm32_initialize((ULONG)USB_DRD_FS, (ULONG)&hpcd_USB_DRD_FS);
    if (status != UX_SUCCESS)
    {
        Error_Handler();
    }

    /* Start the USB hardware */
    HAL_PCD_Start(&hpcd_USB_DRD_FS);
}

void USBX_Device_Process(void)
{
    /* Let USBX process its device tasks. Call periodically in main loop. */
    ux_device_stack_tasks_run();
}

UINT USB_CDC_Transmit(uint8_t *data, ULONG length)
{
    if (g_cdc_acm == UX_NULL)
    {
        return UX_ERROR;
    }
    return ux_device_class_cdc_acm_write(g_cdc_acm, data, length, UX_WAIT_FOREVER);
}
